### ISSUE TITLE
Pie Chart is not showing

### ISSUE THREAD

**Issue by pkumar95** [hassanlatif/chart-marker-clusterer#1]
Hi hassanlatif,

I have tried the example code and trimmed it a little bit. I can see the clustering happening but there is no pie chart on the clustered markers instead its only showing numbers there. Can you please have a look at my html code and tell me what I am doing wrong. Thanks.

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MarkerClusterer v3 Simple Example</title>
    <style>
        body {
            margin: 0;
            padding: 10px 20px 20px;
            font-family: Arial;
            font-size: 16px;
        }
        #map-container {
            padding: 6px;
            border-width: 1px;
            border-style: solid;
            border-color: #ccc #ccc #999 #ccc;
            -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
            -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
            box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
            width: 800px;
        }
        #map {
            width: 800px;
            height: 600px;
        }
    </style>
    <script src="C:\Users\Praveen\Desktop\traffic.json"></script>
    <script type="text/javascript" src="https://www.google.com/jsapi"></script>
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js"></script>
    <script type="text/javascript" src="https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js"></script>
    <script>
        function initialize() {
            var center = new google.maps.LatLng(59.9214, 10.8463);
            var map = new google.maps.Map(document.getElementById('map'), {
                zoom: 12,
                center: center,
                mapTypeId: google.maps.MapTypeId.ROADMAP,
				
            });
            var opt = {
				gridSize: 200
            };
            var markers = [];
            for (var i = 0; i < data.features.length; i++) {
                var accident_injuries = data.features[i].properties["5074"];
                var accident_title = "";
                var accident_lnglat = data.features[i].geometry["coordinates"];
                switch (Number(accident_injuries)) {
                    case 1:
                        accident_title = "Fatal";
                        break;
                    case 3:
                        accident_title = "Serious injuries";
                        break;
                    case 2:
                        accident_title = "Very serious injuries";
                        break;
                    case 5:
                        accident_title = "No injuries";
                        break;
                    case 4:
                        accident_title = "Minor injuries";
                        break;
                    case 6:
                        accident_title = "Not recorded";
                        break;
                }
                var accident_LatLng = new google.maps.LatLng(Number(accident_lnglat[1]), Number(accident_lnglat[0]));
                var marker = new google.maps.Marker({
                    position: accident_LatLng,
                    title: accident_title
                });
                markers.push(marker);
            }
            var markerCluster = new MarkerClusterer(map, markers, opt);
        }
        google.load("visualization", "1", {packages: ["corechart"]});
        google.setOnLoadCallback(initialize);
    </script>

</head>
<body>
<h3>An example of Chart Marker Clusterer</h3>

<div id="map-container">
    <div id="map"></div>
</div>
</body>
</html>

**Comment by hassanlatif** [comment]
Hi, sorry for replying so late. I somehow missed this. I think you are not referencing the correct markerclusterer.js file in <script type="text/javascript" src="https://cdn.rawgit.com/googlemaps/js-marker-clusterer/gh-pages/src/markerclusterer.js">. You should use "https://raw.githubusercontent.com/hassanlatif/google-map-chart-marker-clusterer/master/src/markerclusterer.js" or you can download it and refer to it locally. 

Hope this helps.

**Comment by pkumar95** [comment]
Thanks Hassan. I will try to implement this solution.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by sunilbcone** [comment]
Hi hassanlatif,
I am trying to implement same in angular but it is not working it is showing numbers only. However I have same working code in javascript and html
